pipeline:
  build_aktools:
    image: plugins/docker
    repo: hub.docker.com/gwilmot/ak-tools
    secrets: [ docker_username, docker_password ]
    registry: hub.docker.com
    context: gwilmot/ak-tools
    repo: gwilmot/ak-tools
    tags: latest

    when:
      event: push
