kind: pipeline
name: default
steps:
- name: publish
  image: plugins/docker
  settings:
    repo: centrisolutions/ak-tools
    tags: latest
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password

